version: "3.3"  # optional since v1.27.0
services:
  ingest:
    image: python:3-bullseye
    volumes:
     - ./demo_data:/app/demo_data
    restart: "no"
  terminusdb:
    image: terminusdb/terminusdb-server:dev
    pull_policy: always
    volumes:
      - ./demo_data:/app/demo_data
      - ./tdb_storage:/app/terminusdb/storage
    ports:
      - "6363:6363"
    command: bash /app/demo_data/insert.sh
